# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b282bd4f1bac6fe51622192a1367ddfd1ba7333f12743a16c7053e890973821b0b80772b295b20bdd75e805f4b081f42f729c9c4a498721271920ec4c4f71803

test:
  secret_key_base: 7ebe3b35495ec352c8e47d486faf576a11ca91e143296e15fbca6490326fa538978b69822b58f09d894044b612c5b26b4d21f94921e3e19707aad3ccc741288c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
